### ISSUE TITLE
Repo activity 

### ISSUE THREAD

**Issue by GerkinDev** [tmyt/passport-fido2#1]
Hi,
I'm willing to implement an application using your package, but are you okay to manage issues or merge PRs?

Cheers!

**Comment by tmyt** [comment]
@GerkinDev Sounds good!

**Comment by JamesCullum** [comment]
A proper fido2 passport strategy should utilize the fido2 certified package `fido2-lib` to make it maintainable and allow confidence into its security.

**Comment by tmyt** [comment]
@JamesCullum check `feature/fido2-webauthn` branch. the branch based on `fido2-lib`.
